"""empty message

Revision ID: 13e20608d3d6
Revises: d2d4aad22c26
Create Date: 2024-05-09 14:24:40.418013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e20608d3d6'
down_revision = 'd2d4aad22c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_items', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show_items', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show_items', type_='foreignkey')
    op.drop_column('show_items', 'artist_id')
    # ### end Alembic commands ###
