"""empty message

Revision ID: a033d03b1230
Revises: 85b408f2b06c
Create Date: 2024-05-09 14:02:14.634290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a033d03b1230'
down_revision = '85b408f2b06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_items', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'show_items', 'Show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show_items', type_='foreignkey')
    op.drop_column('show_items', 'show_id')
    # ### end Alembic commands ###
